### PR TITLE
rename LList.iso2 to LList.isoCurried

### PR DESCRIPTION
**Pull request by eed3si9n**
I got confused within only a few days of looking at the PR what `iso2` was, so I am renaming it.

### CODE REVIEW

**Comment by dwijnand** [comment]
I don't think curried is the right word. From https://en.wikipedia.org/wiki/Currying:

> currying is the technique of translating the evaluation of a function that takes multiple arguments (or a tuple of arguments) into evaluating a sequence of functions, each with a single argument.

We're just using a property (official or unofficial, I'm not sure) of Scala to use multiple parameter groups to resolve the type variables with the first function, so that we don't need to guide it with the second.

Given the purpose of the original method, namely deriving an LList representation of a type, I think the multiple parameter groups variant should always be used.

But I didn't want to break your API, and I can't overload because they erase to the same thing, so I just tacked on a "2".

Maybe we should deprecate the old method?

**Comment by eed3si9n** [comment]
Technically speaking a function with multiple parameter groups might not the same as curried function `A1 => A2 => R`, but the distinction here I don't think is that important.
The idiomatic style of Scala function is to accept two parameters in one group unless it's meant to be an infix operator or `while`-replacement DSL. I am ok with breaking API for 0.8.0, but the thing that I am not comfortable with is leaning too much on type inference, which could widen etc unexpectedly.

**Comment by dwijnand** [comment]
> the thing that I am not comfortable with is leaning too much on type inference, which could widen etc unexpectedly.

Without speaking about the design decision in general, but specifically to LList.iso, may I ask you to see if you can find any good examples where type inference of iso is preferable to iso?

**Comment by eed3si9n** [comment]
> Without speaking about the design decision in general..

I am not sure if I am violating this restriction, but I think it's best practice to ascribe types for implicit evidences. I think at some point Scala might introduce that as requirement. This is because capturing `Some` instead of `Option` could introduce subtle bugs.

**Comment by eed3si9n** [comment]
Merging this so I can start the propagation of shaded JSON.

**Comment by dwijnand** [comment]
> I am not sure if I am violating this restriction, but I think it's best practice to ascribe types for implicit evidences. I think at some point Scala might introduce that as requirement. This is because capturing Some instead of Option could introduce subtle bugs.

Yes, especially if you're using that type to drive other implicits (such as in or with shapeless). Btw, there's actually one exception though: values in methods; those don't need type annotations because they're evaluated sequentially only.

**Pull request merged**
