### PR TITLE
use ClassTag instead of ClassManifest

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by eed3si9n** [comment]
Is this thread safe in Scala 2.10? https://issues.scala-lang.org/browse/SI-6240

**Comment by xuwei-k** [comment]
ummm, maybe thread safe :(

- https://gist.github.com/xuwei-k/d0351d27bacd1d81fb00bbf38d658625
- https://github.com/scala/scala/commits/v2.11.8/src/library/scala/reflect/ClassTag.scala

**Comment by eed3si9n** [comment]
More on this topic here - http://docs.scala-lang.org/overviews/reflection/thread-safety.html

**Comment by dwijnand** [comment]
`ClassManifest` is a (deprecated) type alias in Predef for `scala.reflect.ClassManifest`: https://github.com/scala/scala/blob/v2.10.6/src/library/scala/Predef.scala#L105

which is a (deprecated) type alias for `scala.reflect.ClassTag`: https://github.com/scala/scala/blob/v2.10.6/src/library/scala/reflect/package.scala#L28

So, although these types are quite magical in the compiler, I wouldn't be surprised if this change didn't make the code any less thread safe than it is already.

---

Also note that, confusingly, `scala.reflect.Manifest` was un-deprecated, while extending deprecated `scala.reflect.ClassManifest`: https://github.com/scala/scala/blob/v2.10.6/src/library/scala/reflect/Manifest.scala#L42-L44

(And, finally, for some more, confusing, trivia, all these type: `scala.reflect.ClassManifest`, `scala.reflect.ClassTag`, and `scala.reflect.Manifest` are actually in `scala-library` and not in `scala-reflect`, which kind of makes sense otherwise Predef wouldn't be able to define the type alias)

**Comment by dwijnand** [comment]
Further evidence that this change is good-to-go:

> `ClassTag` is an exact drop-in replacement for `ClassManifest`

by @xeno-by in http://stackoverflow.com/questions/12218641/scala-what-is-a-typetag-and-how-do-i-use-it#comment16398232_12232195

**Pull request merged**
