### PR TITLE
upgrade jawn, Scala, sbt, MiMa

### PR DESCRIPTION
**Pull request by SethTisue**
the reason I'm interested in the jawn upgrade is
https://github.com/scala/community-build/pull/1131
but it's almost certainly a good thing regardless

### CODE REVIEW

**Comment by SethTisue** [comment]
CI failure seems to be "[error] java.lang.RuntimeException: mimaPreviousArtifacts not set, not analyzing binary compatibility", mind if I stop here and let you finish it off if you're interested?

**Comment by SethTisue** [comment]
Note that I have no idea what those unused `index` parameters in the diffs are about or whether it's okay they're unused. But the tests pass 🤷

**Comment by eed3si9n** [comment]
There's been previous PRs to update Jawn (https://github.com/eed3si9n/sjson-new/pull/85, https://github.com/eed3si9n/sjson-new/pull/96), but I refrained from it since I was afraid of breaking the bincompat breakage that may leak out to sbt. Maybe it's better to bite the bullet and let the chips fall.

**Comment by SethTisue** [comment]
I think this PR is safe, because you are already using different jawn versions for 2.12 and 2.13, and this PR only modifies 2.13-specific stuff.

No opinion on the other PRs.

**Comment by eed3si9n** [comment]
Right. I guess I did the conditional thing in https://github.com/eed3si9n/sjson-new/pull/106 thanks for the reminder.

**Pull request merged**
